name: Release

on:
  push:
    tags:
    - '*'

jobs:
  pypi-publish:
    runs-on: ubuntu-latest
    if: github.repository == 'julianwachholz/django-autocompletefilter'
    environment:
      name: pypi
      url: https://pypi.org/p/django-autocompletefilter
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -U build setuptools twine wheel

      - name: Build package
        run: |
          python -m build
          twine check dist/*

      - name: Upload packages
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@v1.10.2
