name: Release

on:
  push:
    tags:
      - "*"

jobs:
  pypi-publish:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/') && github.repository == 'julianwachholz/django-autocompletefilter'
    environment:
      name: pypi
      url: https://pypi.org/p/django-autocompletefilter
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -U build setuptools twine wheel

      - name: Build package
        run: |
          python -m build
          twine check dist/*

      - name: Upload packages
        uses: pypa/gh-action-pypi-publish@v1.10.2

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: dist/*
